SERVICES = {
    "📱 T-Mobile / Sprint / MetroPCS": [
        {"id": "tmob_all_models", "name": {"es": "Todos los Modelos (Premium 100% / Sin Garantía)", "en": "All Models (Premium 100% / No Warranty)"}, "price": 95.00, "time": "1-12 Horas"},
        {"id": "tmob_direct_11_14", "name": {"es": "iPhone 11/12/13/14 Series Premium 100% (Sin Garantía)", "en": "iPhone 11/12/13/14 Series Premium 100% (No Warranty)"}, "price": 100.00, "time": "1-24 Horas"},
        {"id": "tmob_direct_15", "name": {"es": "iPhone 15 Series Premium 100% (Sin Garantía)", "en": "iPhone 15 Series Premium 100% (No Warranty)"}, "price": 100.00, "time": "1-24 Horas"},
        {"id": "tmob_direct_16", "name": {"es": "iPhone 16 Series Premium 100% (Sin Garantía)", "en": "iPhone 16 Series Premium 100% (No Warranty)"}, "price": 100.00, "time": "1-24 Horas"},
        {"id": "tmob_direct_17", "name": {"es": "iPhone 17 Series Premium 100% (Sin Garantía)", "en": "iPhone 17 Series Premium 100% (No Warranty)"}, "price": 100.00, "time": "1-24 Horas"},
        {"id": "tmob_slow_12", "name": {"es": "Eligible hasta iPhone 12 (Clean & Paid)", "en": "Eligible up to iPhone 12 (Clean & Paid)"}, "price": 60.00, "time": "1-7 Días"},
        {"id": "tmob_slow_13_14", "name": {"es": "Eligible iPhone 13 & 14 Series (Clean & Paid)", "en": "Eligible iPhone 13 & 14 Series (Clean & Paid)"}, "price": 65.00, "time": "1-5 Días"},
        {"id": "tmob_slow_15", "name": {"es": "Eligible iPhone 15 Series (Clean & Paid)", "en": "Eligible iPhone 15 Series (Clean & Paid)"}, "price": 73.00, "time": "1-5 Días"},
        {"id": "tmob_slow_16", "name": {"es": "Eligible iPhone 16 Series (Clean & Paid)", "en": "Eligible iPhone 16 Series (Clean & Paid)"}, "price": 85.00, "time": "1-5 Días"},
        {"id": "tmob_slow_17", "name": {"es": "Eligible iPhone 17 Series (Clean & Paid)", "en": "Eligible iPhone 17 Series (Clean & Paid)"}, "price": 85.00, "time": "1-5 Días"},
        {"id": "tmob_franklin", "name": {"es": "Franklin Wireless T9 Router/Hotspot Unlock", "en": "Franklin Wireless T9 Router/Hotspot Unlock"}, "price": 13.00, "time": "Minutos"},
        {"id": "tmob_premium_unbarring", "name": {"es": "Premium Unbarring iPhone & Generic (Bloqueado/Robado → Clean)", "en": "Premium Unbarring iPhone & Generic (Blocked/Stolen → Clean)"}, "price": 60.00, "time": "1-12 Horas"},
        {"id": "tmob_unbarring", "name": {"es": "Unbarring iPhone & Generic (ESN → Clean)", "en": "Unbarring iPhone & Generic (ESN → Clean)"}, "price": 37.00, "time": "1-72 Horas"},
        {"id": "tmob_express_all_14", "name": {"es": "Express Todos los Modelos hasta iPhone 14 Pro Max", "en": "Express All Models up to iPhone 14 Pro Max"}, "price": 146.00, "time": "1-12 Horas"},
        {"id": "tmob_express_15pro", "name": {"es": "Express iPhone 15 Pro / 15 Pro Max", "en": "Express iPhone 15 Pro / 15 Pro Max"}, "price": 183.00, "time": "1-12 Horas"},
        {"id": "tmob_express_15", "name": {"es": "Express iPhone 15 / 15 Plus", "en": "Express iPhone 15 / 15 Plus"}, "price": 176.00, "time": "1-12 Horas"},
        {"id": "tmob_express_16", "name": {"es": "Express iPhone 16 / 16 Plus", "en": "Express iPhone 16 / 16 Plus"}, "price": 205.00, "time": "1-24 Horas"},
        {"id": "tmob_express_16pro", "name": {"es": "Express iPhone 16 Pro / 16 Pro Max", "en": "Express iPhone 16 Pro / 16 Pro Max"}, "price": 218.00, "time": "1-12 Horas"},
        {"id": "tmob_express_17", "name": {"es": "Express iPhone 17 / 17 Air ⚡ (Sin Relock)", "en": "Express iPhone 17 / 17 Air ⚡ (No Relock)"}, "price": 248.00, "time": "6-24 Horas"},
        {"id": "tmob_express_17pro", "name": {"es": "Express iPhone 17 Pro ⚡ (Sin Relock)", "en": "Express iPhone 17 Pro ⚡ (No Relock)"}, "price": 270.00, "time": "6-24 Horas"},
        {"id": "tmob_express_17promax", "name": {"es": "Express iPhone 17 Pro Max ⚡ (Sin Relock)", "en": "Express iPhone 17 Pro Max ⚡ (No Relock)"}, "price": 288.00, "time": "6-24 Horas"},
    ],
    "📡 Verizon USA": [
        {"id": "ver_fast_16", "name": {"es": "Unlock hasta Serie 16 (Fast / Eligible 60 días)", "en": "Unlock up to Series 16 (Fast / Eligible 60 Days)"}, "price": 115.00, "time": "1-72 Horas"},
        {"id": "ver_17_unpaid", "name": {"es": "Unlock hasta Serie 17 (Clean & Unpaid / 90% Éxito / Sin Relock)", "en": "Unlock up to Series 17 (Clean & Unpaid / 90% Success / No Relock)"}, "price": 99.00, "time": "1-15 Días"},
        {"id": "ver_convert_eligible", "name": {"es": "Convertir IMEI No Elegible → Elegible (iPhone & Generic)", "en": "Convert Non Eligible IMEI → Eligible (iPhone & Generic)"}, "price": 40.00, "time": "1-7 Días"},
        {"id": "ver_esn_check", "name": {"es": "ESN Check — Clean / Bloqueado / Blacklist (Instant)", "en": "ESN Check — Clean / Blocked / Blacklist (Instant)"}, "price": 1.03, "time": "Minutos"},
        {"id": "ver_finder", "name": {"es": "Finder — Nombre + Número del Primer Dueño", "en": "Finder — First Owner Name + Number"}, "price": 12.00, "time": "2-5 Días"},
        {"id": "ver_unbarring", "name": {"es": "Unbarring iPhone & Generic (ESN → Clean / Sin Relock)", "en": "Unbarring iPhone & Generic (ESN → Clean / No Relock)"}, "price": 77.00, "time": "1-12 Días"},
        {"id": "ver_esn_block", "name": {"es": "Unlock Eligibility Checker iPhone & Generic (Instant)", "en": "Unlock Eligibility Checker iPhone & Generic (Instant)"}, "price": 1.25, "time": "Instant"},
        {"id": "ver_android", "name": {"es": "Android Unlock por IMEI Sin Código (Samsung/Pixel) Clean Only", "en": "Android IMEI Unlock No Code (Samsung/Pixel) Clean Only"}, "price": 147.00, "time": "10-25 Días"},
        {"id": "ver_motorola", "name": {"es": "Motorola — Verizon Unlock Codes", "en": "Motorola — Verizon Unlock Codes"}, "price": 11.00, "time": "10-20 Minutos"},
        {"id": "ver_apple_id", "name": {"es": "Apple Owner ID Info Service (Servicio Rápido)", "en": "Apple Owner ID Info Service (Fast Service)"}, "price": 25.00, "time": "1-12 Horas"},
    ],
    "📶 AT&T USA & México": [
        {"id": "att_mx_6_xs", "name": {"es": "AT&T México — iPhone 6 hasta Xs Max (99% Éxito)", "en": "AT&T Mexico — iPhone 6 to Xs Max (99% Success)"}, "price": 34.90, "time": "1-24 Horas"},
        {"id": "att_mx_11_12", "name": {"es": "AT&T México — iPhone 11/12 Series (99% Éxito)", "en": "AT&T Mexico — iPhone 11/12 Series (99% Success)"}, "price": 43.00, "time": "1-48 Horas"},
        {"id": "att_mx_13", "name": {"es": "AT&T México — iPhone 13 Series (99% Éxito)", "en": "AT&T Mexico — iPhone 13 Series (99% Success)"}, "price": 68.00, "time": "1-24 Horas"},
        {"id": "att_mx_14", "name": {"es": "AT&T México — iPhone 14 Series (99% Éxito)", "en": "AT&T Mexico — iPhone 14 Series (99% Success)"}, "price": 79.00, "time": "1-24 Horas"},
        {"id": "att_mx_15", "name": {"es": "AT&T México — iPhone 15 Series (99% Éxito)", "en": "AT&T Mexico — iPhone 15 Series (99% Success)"}, "price": 88.00, "time": "1-24 Horas"},
        {"id": "att_mx_16", "name": {"es": "AT&T México — iPhone 16 Series (99% Éxito)", "en": "AT&T Mexico — iPhone 16 Series (99% Success)"}, "price": 97.00, "time": "1-24 Horas"},
        {"id": "att_mx_17", "name": {"es": "AT&T México — iPhone 17 Series (99% Éxito)", "en": "AT&T Mexico — iPhone 17 Series (99% Success)"}, "price": 108.00, "time": "Minutos"},
        {"id": "att_clean_refund", "name": {"es": "Clean Check + Unlock (Reembolso si no se completa)", "en": "Clean Check + Unlock (Refund if not completed)"}, "price": 6.00, "time": "Minutos"},
        {"id": "att_clean_checker", "name": {"es": "Status Check + Unlock Rápido 90% (Sin Reembolso)", "en": "Status Check + Unlock Fast 90% (No Refund)"}, "price": 1.50, "time": "Minutos"},
        {"id": "att_past_due_xs", "name": {"es": "Past Due Payments — iPhone hasta Xs Max", "en": "Past Due Payments — iPhone up to Xs Max"}, "price": 45.00, "time": "7-25 Días"},
        {"id": "att_past_due_12", "name": {"es": "Past Due Payments — iPhone 11 hasta 12 Pro Max", "en": "Past Due Payments — iPhone 11 to 12 Pro Max"}, "price": 55.00, "time": "7-25 Días"},
        {"id": "att_past_due_16", "name": {"es": "Past Due Payments — iPhone 13 hasta 16 Pro Max", "en": "Past Due Payments — iPhone 13 to 16 Pro Max"}, "price": 75.00, "time": "1-25 Días"},
        {"id": "att_no_longer_basic", "name": {"es": "No Longer Active / Account 2 Locked (iPhone & Generic)", "en": "No Longer Active / Account 2 Locked (iPhone & Generic)"}, "price": 22.80, "time": "1-10 Días"},
        {"id": "att_no_longer_high", "name": {"es": "No Longer Active Alto Éxito (Todos los Modelos)", "en": "No Longer Active High Success (All Models)"}, "price": 33.00, "time": "1-48 Horas"},
        {"id": "att_post_60", "name": {"es": "Post-Purchase 60 Days (iPhone & Generic)", "en": "Post-Purchase 60 Days (iPhone & Generic)"}, "price": 9.40, "time": "24-72 Horas"},
        {"id": "att_android_unbarring", "name": {"es": "Android Unbarring (Blacklist → Clean)", "en": "Android Unbarring (Blacklist → Clean)"}, "price": 120.00, "time": "1-25 Días"},
        {"id": "att_semi_14", "name": {"es": "Semi Premium hasta Serie 14 (1-55 días hábiles)", "en": "Semi Premium up to Series 14 (1-55 working days)"}, "price": 150.00, "time": "1-10 Días"},
        {"id": "att_semi_15", "name": {"es": "Semi Premium hasta Serie 15 (1-55 días hábiles)", "en": "Semi Premium up to Series 15 (1-55 working days)"}, "price": 245.00, "time": "1-10 Días"},
        {"id": "att_semi_16", "name": {"es": "Semi Premium Serie 16 (1-55 días hábiles)", "en": "Semi Premium Series 16 (1-55 working days)"}, "price": 265.00, "time": "1-10 Días"},
        {"id": "att_unbarring_16_17", "name": {"es": "Unbarring iPhone 16 & 17 (Blacklist → Clean)", "en": "Unbarring iPhone 16 & 17 (Blacklist → Clean)"}, "price": 150.00, "time": "10-25 Días"},
        {"id": "att_apple_id", "name": {"es": "Apple Owner ID Info Service", "en": "Apple Owner ID Info Service"}, "price": 25.00, "time": "6-72 Horas"},
    ],
    "🔍 Checks & Verificaciones": [
        {"id": "chk_honor", "name": {"es": "Honor — Info Check por IMEI & Serial", "en": "Honor — Info Check by IMEI & Serial"}, "price": 1.06, "time": "Instant"},
        {"id": "chk_tmob_esn", "name": {"es": "T-Mobile — ESN Pro Check por IMEI", "en": "T-Mobile — ESN Pro Check by IMEI"}, "price": 1.05, "time": "Instant"},
        {"id": "chk_iphone_carrier", "name": {"es": "iPhone — Carrier / SimLock / Fecha de Compra", "en": "iPhone — Carrier / SimLock / Purchase Date"}, "price": 1.03, "time": "Instant"},
        {"id": "chk_xiaomi_full", "name": {"es": "Xiaomi — Full Device Details (IMEI/Serial/Activación)", "en": "Xiaomi — Full Device Details (IMEI/Serial/Activation)"}, "price": 1.08, "time": "Minutos"},
        {"id": "chk_xiaomi_country", "name": {"es": "Xiaomi — Country Check vía Lock Code", "en": "Xiaomi — Country Check via Lock Code"}, "price": 1.60, "time": "1-2 Horas"},
        {"id": "chk_samsung_simlock", "name": {"es": "Samsung — Sim Lock Status (Locked/Unlocked)", "en": "Samsung — Sim Lock Status (Locked/Unlocked)"}, "price": 1.10, "time": "Instant"},
        {"id": "chk_samsung_knox", "name": {"es": "Samsung — Knox Guard / Carrier / Warranty Check", "en": "Samsung — Knox Guard / Carrier / Warranty Check"}, "price": 1.11, "time": "Instant"},
        {"id": "chk_pixel", "name": {"es": "Google Pixel — Activation / Warranty / Carrier Check", "en": "Google Pixel — Activation / Warranty / Carrier Check"}, "price": 1.10, "time": "Minutos"},
        {"id": "chk_metropcs_app", "name": {"es": "MetroPCS — Device Unlock App Check + Unlock (180 días activado)", "en": "MetroPCS — Device Unlock App Check + Unlock (180 days active)"}, "price": 7.35, "time": "1-72 Horas"},
        {"id": "chk_metropcs_android", "name": {"es": "MetroPCS — Android APP Unlock (180 días activado)", "en": "MetroPCS — Android APP Unlock (180 days active)"}, "price": 8.00, "time": "Minutos"},
        {"id": "chk_tmob_contract", "name": {"es": "T-Mobile — Eligibility Checker (Contract/Finance/GSMA)", "en": "T-Mobile — Eligibility Checker (Contract/Finance/GSMA)"}, "price": 1.17, "time": "Minutos"},
        {"id": "chk_ver_esn", "name": {"es": "Verizon — ESN Check Clean/Bloqueado/Blacklist", "en": "Verizon — ESN Check Clean/Blocked/Blacklist"}, "price": 1.03, "time": "Minutos"},
        {"id": "chk_ver_eligibility", "name": {"es": "Verizon — Unlock Eligibility Checker", "en": "Verizon — Unlock Eligibility Checker"}, "price": 1.25, "time": "Instant"},
        {"id": "chk_spectrum", "name": {"es": "Spectrum — iPhone Unlock Eligibility Check", "en": "Spectrum — iPhone Unlock Eligibility Check"}, "price": 1.08, "time": "Instant"},
        {"id": "chk_cricket", "name": {"es": "Cricket — Unlock Eligibility Checker iPhone & Generic", "en": "Cricket — Unlock Eligibility Checker iPhone & Generic"}, "price": 1.70, "time": "Instant"},
        {"id": "chk_lpro", "name": {"es": "LPro A12+ — Rebypass hasta iOS 18.1.1 con/sin Network", "en": "LPro A12+ — Rebypass up to iOS 18.1.1 with/without Network"}, "price": 15.00, "time": "Instant"},
    ],
    "🔓 Unbarring & ESN Cleaning": [
        {"id": "unb_tmob_premium", "name": {"es": "T-Mobile Premium Unbarring (Bloqueado/Robado → Clean)", "en": "T-Mobile Premium Unbarring (Blocked/Stolen → Clean)"}, "price": 60.00, "time": "1-12 Horas"},
        {"id": "unb_tmob", "name": {"es": "T-Mobile Unbarring (ESN → Clean)", "en": "T-Mobile Unbarring (ESN → Clean)"}, "price": 37.00, "time": "1-72 Horas"},
        {"id": "unb_att_android", "name": {"es": "AT&T Android Unbarring (Blacklist → Clean)", "en": "AT&T Android Unbarring (Blacklist → Clean)"}, "price": 120.00, "time": "1-25 Días"},
        {"id": "unb_cricket", "name": {"es": "Cricket Unbarring hasta iPhone 15 Pro Max (Blacklist/Robado → Clean)", "en": "Cricket Unbarring up to iPhone 15 Pro Max (Blacklist/Stolen → Clean)"}, "price": 60.00, "time": "2-7 Días"},
        {"id": "unb_att_16_17", "name": {"es": "AT&T Unbarring iPhone 16 & 17 (Blacklist → Clean)", "en": "AT&T Unbarring iPhone 16 & 17 (Blacklist → Clean)"}, "price": 150.00, "time": "10-25 Días"},
        {"id": "unb_verizon", "name": {"es": "Verizon Unbarring iPhone & Generic (ESN → Clean / Sin Relock)", "en": "Verizon Unbarring iPhone & Generic (ESN → Clean / No Relock)"}, "price": 77.00, "time": "1-12 Días"},
    ],
}
